# Generated by Django 6.0.7 on 2026-07-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0002_alter_quote_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('born', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('famous_for', models.TextField()),
                ('quote', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='notable_quotes.author'),
        ),
    ]
