# Generated by Django 6.0.7 on 2026-07-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0003_author_alter_quote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='quote',
        ),
    ]
