# Generated by Django 6.0.7 on 2026-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0003_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
