# Generated by Django 6.0.7 on 2026-07-18 19:35
from django.db import migrations

"""
schema_editor is unused in this migration because we are changing data, not database structure
It is included because Django's RunPython migration API provides it automatically
"""
def link_quotes_to_authors(apps, schema_editor):

    Quote = apps.get_model(
        "notable_quotes",
        "Quote"
    )

    Author = apps.get_model(
        "notable_quotes",
        "Author"
    )

    for quote in Quote.objects.all():
        author = Author.objects.get(name=quote.author)

        print(
            f"{quote.author} found → Author ID {author.id}"
        )
        


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0004_alter_author_born'),
    ]

    operations = [
        migrations.RunPython(link_quotes_to_authors),
    ]