# Generated by Django 6.0.7 on 2026-07-18 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0005_auto_20260718_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='notable_quotes.author'),
        ),
    ]
