# Generated by Django 6.0.7 on 2026-07-18 20:49

from django.db import migrations

# This migration populates a foreign key in the Quotes table with the author object/id from the Author table
def populate_author_foreign_key(apps, schema_editor):
    
    Quote = apps.get_model(
        "notable_quotes", 
        "Quote"
        )
    
    Author = apps.get_model(
        "notable_quotes",
        "Author"
    )

    for quote in Quote.objects.all():

        # Assigning author object from authors table whose name matches the author from Quote's current author column
        author = Author.objects.get(
            name=quote.author
        )

        quote.author_temp = author
        quote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0006_quote_author_temp'),
    ]

    operations = [
        migrations.RunPython(populate_author_foreign_key),
    ]
