# Generated by Django 6.0.7 on 2026-07-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0007_auto_20260718_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
    ]
