# Generated by Django 6.0.7 on 2026-07-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0008_remove_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author_temp',
            new_name='author',
        ),
    ]
