# Generated by Django 6.0.7 on 2026-07-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0008_remove_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author_temp',
            new_name='author',
        ),

        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quotes',
                to='notable_quotes.author',
            ),
        ),
    ]
