# Generated by Django 6.0.7 on 2026-07-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notable_quotes', '0009_auto_20260718_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.ManyToManyField(related_name='quotes', to='notable_quotes.category'),
        ),
    ]
